name: Build docker
description: Builds and push docker image

inputs:
  dockerhub_username:
    description: Dockerhub username
    required: true
  dockerhub_token:
    description: Dockerhub PAT
    required: true

outputs:
  image_name:
    description: Image name
    value: ${{ steps.set_outputs.outputs.image_name }}
  image_tag:
    description: Image tag
    value: ${{ steps.set_outputs.outputs.new_tag }}
  image_digest:
    description: Image digest
    value: ${{ steps.set_outputs.outputs.new_digest }}

runs:
  using: composite

  steps:
    - name: Login to Github Container Registry
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee  # v4.2.0
      with:
        registry: ${{ env.registry }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Login to dhi.io Container Registry
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee  # v4.2.0
      with:
        registry: dhi.io
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b  # v6.2
      with:
        github_token: ${{ github.token }}

    - name: Build docker and push
      id: build
      uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf  # v7.2.0
      with:
        context: .
        push: true
        tags: ${{ env.registry }}/${{ github.repository }}:${{ steps.tag_version.outputs.new_tag }} , ${{ env.registry }}/${{ github.repository }}:latest

    - name: Set outputs
      id: set_outputs
      shell: bash
      run: |
        echo "image_name=${REGISTRY}/${{ github.repository }}"     >> $GITHUB_OUTPUT 
        echo "new_digest=${STEPS_BUILD_OUTPUTS_DIGEST}"            >> $GITHUB_OUTPUT
        echo "new_tag=${STEPS_TAG_VERSION_OUTPUTS_NEW_TAG}"        >> $GITHUB_OUTPUT
      env:
        REGISTRY: ${{ env.registry }}
        STEPS_BUILD_OUTPUTS_DIGEST: ${{ steps.build.outputs.digest }}
        STEPS_TAG_VERSION_OUTPUTS_NEW_TAG: ${{ steps.tag_version.outputs.new_tag }}

    - name: Add summary of build
      id: summary
      shell: bash
      run: |
        echo "### Image release info"                                 >> $GITHUB_STEP_SUMMARY
        echo "- Image name: ${REGISTRY}/${{ github.repository }}"     >> $GITHUB_STEP_SUMMARY 
        echo "- Digest: ${STEPS_BUILD_OUTPUTS_DIGEST}"                >> $GITHUB_STEP_SUMMARY
        echo "- Tag: ${STEPS_TAG_VERSION_OUTPUTS_NEW_TAG}"            >> $GITHUB_STEP_SUMMARY
      env:
        REGISTRY: ${{ env.registry }}
        STEPS_BUILD_OUTPUTS_DIGEST: ${{ steps.build.outputs.digest }}
        STEPS_TAG_VERSION_OUTPUTS_NEW_TAG: ${{ steps.tag_version.outputs.new_tag }}