import type { ByggRapport } from "../lib/schema/byggRapportSchema"

const mockByggRapport: ByggRapport = {
  rapportType: "BYG0011",
  tittel: "Bygningsrapport – Storgata 1",
  kommune: { nr: "0301", navn: "Oslo" },
  koordinatsystem: "EUREF89 UTM sone 32",
  locale: "nb",
  generertTidspunkt: "2026-07-10T12:00:00Z",
  utvalgskriterier: {
    omfang: {
      bestaaendeBygg: true,
      utgaatteBygg: false,
      bygninger: true,
      bygningsendringer: true,
      frededeBygninger: "Inkluder",
    },
    bygning: {
      bygningsnr: "12345678",
      bygningstyper: [{ kode: 111, navn: "Enebolig" }],
      lopenr: 1,
    },
    adresse: {
      adressekode: "10001",
      bruksenhetsnr: "H0101",
      adressenavn: "Storgata",
      nr: 1,
      bokstav: null,
      utenBokstav: true,
      tilleggsnavn: null,
    },
    matrikkelenhet: { gnr: 208, bnr: 12, fnr: null, snr: null },
    hjemmelshaver: {
      foedselsEllerOrgnr: "01019012345",
      etternavn: "Nordmann",
      fornavn: "Ola",
    },
    bygningsstatus: {
      naavaerende: ["Tatt i bruk", "Ferdigattest"],
      tidligere: ["Igangsettingstillatelse"],
      periodeFra: "2019-01-01",
      periodeTil: "2026-07-10",
    },
    sokevindu: {
      nedreVenstre: { nord: 6642000, ost: 597000 },
      ovreHoeyre: { nord: 6643000, ost: 598000 },
    },
    subrapporter: {
      etasjer: true,
      bruksenheter: true,
      tiltakshavere: true,
      kontaktpersoner: true,
      hjemmelshavere: true,
      kulturminner: true,
    },
  },
  bygninger: [
    {
      id: 1,
      bygningsnr: "12345678",
      bygningstype: { kode: 111, navn: "Enebolig" },
      adresseverdig: true,
      naeringsgruppe: "Bolig",
      matrikkelenhet: "208/12",
      endringer: [
        {
          id: 1001,
          bygningId: 1,
          lopenr: 1,
          endringskode: null,
          bygningsstatus: {
            kode: 4,
            kortkode: "TB",
            navn: "Tatt i bruk",
            bestaaende: true,
          },
          antallBoenheter: 1,
          bruksareal: { bolig: 140, annet: 35, totalt: 175 },
          bruttoareal: { bolig: 158, annet: 44, totalt: 202 },
          bebygdAreal: 95,
          koordinat: { nord: 6642100, ost: 597400 },
          datoer: {
            rammetillatelse: "2019-03-15",
            igangsettingstillatelse: "2019-05-01",
            midlertidigBrukstillatelse: null,
            ferdigattest: "2020-08-20",
            tattIBruk: "2020-09-01",
            utgaattRevet: null,
          },
          etasjeplan: [
            {
              etasjeplan: "Hovedetasje",
              etasje: 1,
              antallBoenheter: 1,
              bruksareal: { bolig: 80, annet: 10, totalt: 90 },
              bruttoareal: { bolig: 90, annet: 12, totalt: 102 },
            },
            {
              etasjeplan: "Annenetasje",
              etasje: 2,
              antallBoenheter: 0,
              bruksareal: { bolig: 60, annet: 10, totalt: 70 },
              bruttoareal: { bolig: 68, annet: 12, totalt: 80 },
            },
            {
              etasjeplan: "Loft",
              etasje: 3,
              antallBoenheter: 0,
              bruksareal: { bolig: 0, annet: 15, totalt: 15 },
              bruttoareal: { bolig: 0, annet: 20, totalt: 20 },
            },
          ],
          bruksenheter: [
            {
              bruksenhetsnr: "H0101",
              type: "Bolig",
              matrikkelenhet: { gnr: 208, bnr: 12 },
              bruksareal: 145,
              antallRom: 5,
              kjokkentilgang: true,
              antallBad: 2,
              antallWc: 2,
              adresse: "Storgata 1, 0155 Oslo",
              egenregistrert: {
                byggeaar: 2020,
                vannforsyning: {
                  data: "Tilknyttet offentlig vannverk",
                  erGjeldende: true,
                  gyldighetsperiode: { gyldigFra: null, gyldigTil: null },
                },
                avlop: {
                  data: "Tilknyttet offentlig avløpsnett",
                  erGjeldende: true,
                  gyldighetsperiode: { gyldigFra: null, gyldigTil: null },
                },
                energikilder: [
                  {
                    data: "Elektrisitet",
                    erGjeldende: true,
                    gyldighetsperiode: { gyldigFra: null, gyldigTil: null },
                  },
                ],
                oppvarming: [
                  {
                    data: "Varmepumpe",
                    erGjeldende: true,
                    gyldighetsperiode: { gyldigFra: null, gyldigTil: null },
                  },
                ],
              },
            },
          ],
          tiltakshavere: [
            {
              rolle: "Tiltakshaver",
              eierIdent: "01019012345",
              navn: "Ola Nordmann",
              adresselinje1: "Storgata 1",
              adresselinje2: null,
              adresselinje3: null,
              postnummeromradenr: "0155",
              postnummeromradenavn: "Oslo",
              land: "Norge",
              bruksenhetsnr: "H0101",
              datofra: "2019-03-15",
              datofraSOSI: "20190315",
              harDatofra: true,
              kategorikode: "FYSISK_PERSON",
              kontaktpersonKode: null,
              statuskode: "AKTIV",
              eierErUtgatt: false,
            },
          ],
          kontaktpersoner: [
            {
              rolle: "Kontaktperson",
              eierIdent: "987654321",
              navn: "Byggmester Bob AS",
              adresselinje1: "Håndverkerveien 5",
              adresselinje2: null,
              adresselinje3: null,
              postnummeromradenr: "0666",
              postnummeromradenavn: "Oslo",
              land: "Norge",
              bruksenhetsnr: null,
              datofra: "2019-05-01",
              datofraSOSI: "20190501",
              harDatofra: true,
              kategorikode: "JURIDISK_PERSON",
              kontaktpersonKode: "ANSVARLIG_SOKER",
              statuskode: "AKTIV",
              eierErUtgatt: false,
            },
          ],
          hjemmelshavere: [
            {
              eierIdent: "01019012345",
              navn: "Ola Nordmann",
              andelTeller: 1,
              andelNevner: 2,
              eierforhold: "Eier",
              adresselinje1: "Storgata 1",
              adresselinje2: null,
              adresselinje3: null,
              postnummer: "0155",
              poststed: "Oslo",
              land: "Norge",
              statuskode: "AKTIV",
              eierErUtgatt: false,
              datofra: "2019-01-10",
              datotil: null,
              kategorikode: "FYSISK_PERSON",
              bruksenhetsnr: "H0101",
              harAndel: true,
              erSelveier: true,
              matrikkelenhet: { gnr: 208, bnr: 12, fnr: null, snr: null },
            },
            {
              eierIdent: "02028023456",
              navn: "Kari Nordmann",
              andelTeller: 1,
              andelNevner: 2,
              eierforhold: "Eier",
              adresselinje1: "Storgata 1",
              adresselinje2: null,
              adresselinje3: null,
              postnummer: "0155",
              poststed: "Oslo",
              land: "Norge",
              statuskode: "AKTIV",
              eierErUtgatt: false,
              datofra: "2019-01-10",
              datotil: null,
              kategorikode: "FYSISK_PERSON",
              bruksenhetsnr: "H0101",
              harAndel: true,
              erSelveier: true,
              matrikkelenhet: { gnr: 208, bnr: 12, fnr: null, snr: null },
            },
          ],
          kulturminner: [
            {
              id: "KM-12345",
              navn: "Storgata 1",
              status: "Regulert",
              kategori: "SEFRAK-registrert bygning",
            },
          ],
        },
      ],
    },
  ],
}

export default mockByggRapport
