import { z } from "@hono/zod-openapi"

const byggTypeMap = new Map<string, string>([
  [" ", "IkkeValgt"],
  ["111", "Enebolig"],
  ["112", "Eneboligmhybelsokkelleil"],
  ["113", "Vaningshus"],
  ["121", "TomannsboligVertikaldelt"],
  ["122", "Tomannsbolighorisontaldelt"],
  ["123", "VaningshTomannsbVertikal"],
  ["124", "Vaningshtomannsbhorisont"],
  ["131", "Rekkehus"],
  ["133", "KjedeAtriumhus"],
  ["135", "Terrassehus"],
  ["136", "Andresmahusm3boligerelfl"],
  ["141", "Boligblokkpa2etasjer"],
  ["142", "Boligblokkpa3og4etasjer"],
  ["143", "Boligblokkpa5etasjelmer"],
  ["144", "Sambygdboligbyggpa2etasje"],
  ["145", "Sambygdboligbyggpa34etg"],
  ["146", "Sambygdboligbpa5etgelm"],
  ["151", "TrygdebaldershjemHVPUbol"],
  ["152", "Studenthjemstudentboliger"],
  ["159", "Annenbygningforbofellesskap"],
  ["161", "Fritidsbygghyttersommerhol"],
  ["162", "Helarsbbenyttessomfritidsb"],
  ["163", "Vaninghbenyttessomfritidsb"],
  ["171", "Seterhusselrorbuol"],
  ["172", "Skogsogutmarkskoiegamme"],
  ["181", "Garasjeuthusannekstilbolig"],
  ["182", "Garasjeuthannekstilfritidb"],
  ["183", "Naustbathussjøbu"],
  ["193", "Boligbrakker"],
  ["199", "Annenboligbygsekreindrift"],
  ["211", "Fabrikkbygning"],
  ["212", "Verkstedbygning"],
  ["214", "Bygningforrenseanlegg"],
  ["216", "Bygnforvannforsblapumpest"],
  ["219", "Annenindustribygning"],
  ["221", "KraftstasjonME15000kVA"],
  ["223", "TransformatorstasjME10000kVA"],
  ["229", "Annenenergiforsyningsbygning"],
  ["231", "Lagerhall"],
  ["232", "KjoleOgFryselager"],
  ["233", "Silobygning"],
  ["239", "Annenlagerbygning"],
  ["241", "Husfordyrlandbrlagersilo"],
  ["243", "Veksthus"],
  ["244", "Driftsbfiskefangstoppdr"],
  ["245", "Naustredskapshusforfiske"],
  ["248", "Annenfiskeriogfangstbygn"],
  ["249", "Annenlandbruksbygning"],
  ["311", "Kontorogadmbygningradhus"],
  ["312", "Bankbygningposthus"],
  ["313", "RadioogTVhus"],
  ["319", "Annenkontorbygning"],
  ["321", "KjopesenterVarehus"],
  ["322", "Butikkbygning"],
  ["323", "Bensinstasjon"],
  ["329", "Annenforretningsbygning"],
  ["330", "Messeogkongressbygning"],
  ["411", "Ekspbygnflytermkontrtarn"],
  ["412", "JernbaneogTbanestasjon"],
  ["415", "Godsterminal"],
  ["416", "Postterminal"],
  ["419", "Annenekspogterminalbygning"],
  ["429", "Annentelekommunikasjonsbygn"],
  ["431", "Parkeringshus"],
  ["439", "Annengarasjehangarbygning"],
  ["441", "Biltilsynsbygning"],
  ["449", "AnnenVegOgTrafikktilsbygning"],
  ["511", "Hotellbygning"],
  ["512", "Motellbygning"],
  ["519", "Annenhotellbygning"],
  ["521", "Hospitspensjonat"],
  ["522", "Vandreferiehjem"],
  ["523", "Appartement"],
  ["524", "Campingutleiehytte"],
  ["529", "Annenbygningforovernatting"],
  ["531", "Restaurantbygningkafebygning"],
  ["532", "SentralkjokkenKantinebygning"],
  ["533", "GatekjokkenKioskbygning"],
  ["539", "Annenrestaurantbygning"],
  ["611", "Lekepark"],
  ["612", "Barnehage"],
  ["613", "Barneskole"],
  ["614", "Ungdomsskole"],
  ["615", "Kombbarneogungdomsskole"],
  ["616", "Videregaendeskole"],
  ["619", "Annenskolebygning"],
  ["621", "Univhøgskolemauditorleses"],
  ["623", "Laboratoriebygning"],
  ["629", "AnnenUniversitetHogskolebygn"],
  ["641", "Museumkunstgalleri"],
  ["642", "Bibliotekmediatek"],
  ["643", "Zoologiskbotaniskhagebyg"],
  ["649", "Annenmuseumbiblioteksbygning"],
  ["651", "Idrettshall"],
  ["652", "Ishall"],
  ["653", "Svømmehall"],
  ["654", "Tribuneogidrettsgarderobe"],
  ["655", "Helsestudio"],
  ["659", "Annenidrettsbygning"],
  ["661", "Kinoteateroperakonsertbygn"],
  ["662", "Samfunnshusgrendehus"],
  ["663", "Diskotekungdomsklubb"],
  ["669", "Annetkulturhus"],
  ["671", "Kirkekapell"],
  ["672", "Bedehusmenighetshus"],
  ["673", "Krematgravkapellbarehus"],
  ["674", "Synagogemoske"],
  ["675", "Kloster"],
  ["679", "Annenbygnforreligiøsakt"],
  ["719", "Sykehus"],
  ["721", "Sykehjem"],
  ["722", "Boogbehandlingssenter"],
  ["723", "Rehabiliterinstitusjonkurbad"],
  ["729", "Annetsykehjem"],
  ["731", "Klinikklegekontorlegesenter"],
  ["732", "Helsesosialsenthelsestasj"],
  ["739", "Annenprimærhelsebygning"],
  ["819", "Fengselsbygning"],
  ["821", "Politistasjon"],
  ["822", "Brannstasjonambulansestasjon"],
  ["823", "Fyrstasjonlosstasjon"],
  ["824", "Stasjforradarovvavflysk"],
  ["825", "Tilfluktsrombunker"],
  ["829", "Annenberedskapsbygning"],
  ["830", "Monument"],
  ["840", "Offentligtoalett"],
  ["999", "Ukjent"],
])

export const bygningstypeSchema = z
  .object({
    kode: z.enum([...byggTypeMap.keys()]).meta({ example: "111" }),
    navn: z.string().min(1).meta({ example: "Enebolig" }),
  })
  .meta({ id: "ByggBygningstype" })

export type Bygningstype = z.infer<typeof bygningstypeSchema>
